ShopCRM/ShopCRM.MVC/Controllers/SaleController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using ShopCRM.Application.UseCases.Product.Queries;
using ShopCRM.Application.UseCases.SaleItem.Commands;
using ShopCRM.Application.UseCases.Sales.Commands;
using ShopCRM.Application.UseCases.Sales.Queries;
using ShopCRM.Domain.Entities.ViewModels;

namespace ShopCRM.MVC.Controllers
{
    public class SaleController : Controller
    {
        private readonly IMediator _mediator;

        public SaleController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new CreateSaleViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSaleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }


            if (model.SaleItems.Count == 0)
            {
                ModelState.AddModelError(string.Empty, "Add 1 or more items");

                return View(model);
            }
            else
            {
                var saleResponse = await _mediator.Send(new CreateSaleCommand
                {
                    SalesRepId = model.SalesRepId,
                    LocationId = model.LocationId
                });

                foreach (var saleItem in model.SaleItems)
                {
                    var saleItemResponse = await _mediator.Send(new CreateSaleItemCommand
                    {
                        SaleId = saleResponse,
                        ProductId = saleItem.ProductId,
                        Quantity = saleItem.Quantity
                    });

                    if (!saleItemResponse.IsSuccess)
                    {
                        ModelState.AddModelError(string.Empty, saleItemResponse.Message);
                        
                        return View(model);
                    }
                }

                return RedirectToAction("All", "Sales");
            }
        }

        //[HttpGet]
        //public async Task<IActionResult> SearchProducts(string searchTerm)
        //{
        //    var query = new SearchProductQuery { SearchTerm = searchTerm };
        //    var products = await _mediator.Send(query);

        //    return Json(products);
        //}

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var sales = await _mediator.Send(new GetAllSalesQuery());

            return View(sales);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid Id)
        {
            var sale = await _mediator.Send(new GetSaleByIdQuery { SaleId = Id });

            return View(sale);
        }
    }
}

ShopCRM/ShopCRM.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopCRM.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShopCRM.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shop-CRM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AllUsers">
                                Employees
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Location" asp-action="All">
                                Locations
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="All">
                                Categories
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="All">
                                Products
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Sale" asp-action="All">
                                Sales
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Shop CRM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>